### ISSUE TITLE
Possibility for collaboration

### ISSUE THREAD

**Issue by nmandery** [neiybor/h3o_polars_ext#1]
Hi, I just stumbled over your project here when checking the list of projects dependent on `h3o`. I am implementing something related to what you are starting here - so maybe it could be helpful for you. It is more of a hobby project I try to work on when I find the time for it. Maybe parts of this could be helpful for you:

* [h3arrow](https://github.com/nmandery/h3arrow) - is a rust library is a integration of `h3o` with `arrow2`. It already exposes quite a few algorithms. It is not yet on crates.io, but I want to push it the next few days. Has some integration with geoarrow
* [h3ronpy](https://github.com/nmandery/h3ronpy) - is a python extension bringing the former library to python using `pyarrow` and some wrappers for `pandas` and `polars`

**Comment by seanlane** [comment]
Hey Nico, thanks for reaching out, this is great news!

I actually did come across your work when I was trying discover any prior art for implementing H3 functionality with polars dataframes. If I recall correctly, I think I saw that `h3ronpy` was using the `h3ron` library at the time, or at least I assumed as much and then saw the note on the `h3ron` README that the project was in maintenance mode.

So from there, I believe I assumed that work would be stopping on `h3ronpy` and hadn't seen that you were in the midst of rewriting it to use `h3arrow` and `h3o`.

Given that it's pretty much what we were looking for, and that you're much farther along in implementing the H3 API, we'll probably pivot to using `h3ronpy` and will archive/deprecate this `h3o_polars_ext` project. And we'll work to report any issues and contribute code where we can. Thanks again, looking forward to getting familiar with `h3ronpy` more :)

**Comment by nmandery** [comment]
The naming situation maybe is a bit confusing - I switched to `h3o` from `h3ron` a while ago, but did not want to change the name `h3ronpy` as it was already used in a few other projects. The switch itself took quite a while as I got sidetracked by other things while after I started the migration.

I must confess I feel a bit bad now as I did not want to stop your project here :wink:  Looking forward to your contributions  - there certainly is quite some room for further improvements.

**Comment by seanlane** [comment]
> The naming situation maybe is a bit confusing - I switched to h3o from h3ron a while ago, but did not want to change the name h3ronpy as it was already used in a few other projects.

Yeah, that makes sense, I think I would've done the same as well, it was my own assumptions that led me astray.

> I must confess I feel a bit bad now as I did not want to stop your project here

Please don't, I'm happy to see that there's a project filling the need 😄

**Comment by nmandery** [comment]
Great. It is also really interesting for me to see where my project is getting used.
